### ISSUE TITLE
ansible-galaxy : command not found

### ISSUE THREAD

**Issue by lekeCoder** [macstadium/ansible-playbook-osx-ci-setup#3]
I followed the steps in the setup in the README file and when l try to run `ansible-galaxy install -r requirements.yml` l keep getting the error `ansible-galaxy : command not found`.

Please help

**Comment by ispasov** [comment]
Hi @lekeCoder,

`ansible-galaxy` is part of the Ansible installation. Make sure you have [installed Ansible](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html) and that it can be found in the PATH env variable.
